import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        maven {
            url = uri('https://redirector.gvt1.com/edgedl/android/maven2')
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'androidx.*'
                includeGroupByRegex 'com\\.google\\.testing\\.platform.*'
            }
        }
        maven { url = uri('https://maven.aliyun.com/repository/public') }
        google()
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'com.android.application') {
                useModule("com.android.tools.build:gradle:${requested.version}")
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            url = uri('https://redirector.gvt1.com/edgedl/android/maven2')
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'androidx.*'
                includeGroupByRegex 'com\\.google\\.testing\\.platform.*'
            }
        }
        maven { url = uri('https://maven.aliyun.com/repository/public') }
        google()
        mavenCentral()
    }
}

rootProject.name = 'fnvideo'
include ':app'
